### ISSUE TITLE
Not showing Explorer when using AuthenticationClass

### ISSUE THREAD

**Issue by codemonkeyneo** [Luracast/Restler-API-Explorer#15]
I'm trying to secure a couple of our API endpoints and it works as per the examples (_005_protected_api) but I have found that the explorer will then not show any of the endpoints created.

I have added the Authentication class into index.php
```
$r->addAuthenticationClass('MySimpleAuth');
```

but then looking at the explorer to see the swagger style documentation , I get

```
200 : OK ../resources.json
```

Is this a bug or a step I have missed.

Cheers

codemonkeyneo

**Comment by Arul-** [comment]
Make sure that hide protected option is turned off

    Luracast\Restler\Resources::$hideProtected = false;

Starting from Restler 3.0 RC6 Restler repository itself contains a class called `Explorer` which has the latest version of explorer in built. Try that instead! That also has a similar feature

    Luracast\Restler\Explorer::$hideProtected = false;

**Comment by codemonkeyneo** [comment]
Thanks for quick reply. I tried adding the above into index.php and its still the same. I have around 9 normal endpoints and one declared as protected. I will continue to investigate and if I do solve it make sure I come back here :). Thanks
