### ISSUE TITLE
hiding certain API's or endpoints

### ISSUE THREAD

**Issue by alexkb** [Luracast/Restler-API-Explorer#17]
We're trying to hide certain API's or endpoints (such as our authentication class) from the generated Swagger UI documentation. What is the correct way to do this?

I looked around, and there seems to be [some documentation on using the annotation] (https://github.com/martypitt/swagger-springmvc/issues/447) `@ApiOperation(hidden=true)`. We've tried the hidden setting, but it doesn't seem to work too well.

Should we be hiding out authentication class a different way?

**Comment by Arul-** [comment]
If you are using explorer with SpringMVC the above mentioned documentation will work

But if you are using Restler, do the following instead

if you are using Restler 3.0 RC6 and above, you should be using the `Explorer` class

```php
use Luracast\Restler\Restler;
use Luracast\Restler\Explorer;

Explorer::$excludedPaths = array('some/path','another');

$r = new Restler();

$r->addAPIClass('improved\\Authors');
$r->addAPIClass('Explorer');
$r->handle();
```

If you are using Restler 3.0 RC5 and below, you should be using the `Resources` class

```php
use Luracast\Restler\Restler;
use Luracast\Restler\Resources;

Resources::$excludedPaths = array('some/path','another');

$r = new Restler();

$r->addAPIClass('improved\\Authors');
$r->addAPIClass('Resources');
$r->handle();
```

**Comment by alexkb** [comment]
@Arul- : thanks, that worked great!
