### ISSUE TITLE
Documentation for protected functions

### ISSUE THREAD

**Issue by roydekleijn** [Luracast/Restler-API-Explorer#19]
Hi,

How can we create documentation for protected functions?

Thanks,

**Comment by Arul-** [comment]
Resources class hides the protected methods by default

``` php
use Luracast\Restler\Resources;

Resources::$hideProtected = false;
```

Rest is similar to public api methods :)

**Comment by roydekleijn** [comment]
Awesome.. should we add this to the documentation ?
